const cocteles = [
    {
      nombre: 'Mojito',
      metodo: 'Mezclar y macerar',
      ingredientes: '2 oz de ron blanco, 1 oz de jugo de limón, 2 cucharaditas de azúcar, hojas de menta, agua con gas',
      cristaleria: 'Vaso alto',
      garnish: 'Hoja de menta y rodaja de limón',
      categoria: 'clasicos',
      imagen: '/mojito.jpg',
    },
    {
      nombre: 'Margarita',
      metodo: 'Agitar y colar',
      ingredientes: '2 oz de tequila, 1 oz de jugo de limón, 1 oz de jarabe de agave, sal',
      cristaleria: 'Copa de margarita',
      garnish: 'Rodaja de limón',
      categoria: 'clasicos',
      imagen: '/margarita.jpg',
    },
   
    {
      nombre: 'Old Fashioned',
      metodo: 'Mezclar y servir en vaso bajo',
      ingredientes: '2 oz de whisky, 1 terrón de azúcar, 2-3 dashes de angostura, twist de naranja',
      cristaleria: 'Vaso Old Fashioned',
      garnish: 'Twist de naranja y cereza',
      categoria: 'clasicos',
      imagen: '/oldFashioned.jpg',
    },
    {
      nombre: 'Negroni',
      metodo: 'Revolver y servir en vaso bajo',
      ingredientes: '1 oz de ginebra, 1 oz de Campari, 1 oz de vermut rojo',
      cristaleria: 'Vaso Old Fashioned',
      garnish: 'Twist de naranja',
      categoria: 'clasicos',
      imagen: '/negroni.jpg',
    },
    {
      nombre: 'Martini',
      metodo: 'Agitar y servir en copa de martini',
      ingredientes: '2.5 oz de ginebra, 0.5 oz de vermut seco',
      cristaleria: 'Copa de martini',
      garnish: 'Aceituna o twist de limón',
      categoria: 'clasicos',
      imagen: '/martini.jpg',
    },
    
    {
      nombre: 'Cosmopolitan',
      metodo: 'Agitar y servir en copa de martini',
      ingredientes: '1.5 oz de vodka, 1 oz de Cointreau, 0.5 oz de jugo de lima, 1.5 oz de jugo de arándano',
      cristaleria: 'Copa de martini',
      garnish: 'Twist de lima',
      categoria: 'clasicos',
      imagen: '/cosmopolitan.jpg',
    },
    {
      nombre: 'Daiquiri',
      metodo: 'Agitar y servir en copa de cóctel',
      ingredientes: '2 oz de ron blanco, 1 oz de jugo de lima, 0.75 oz de jarabe simple',
      cristaleria: 'Copa de cóctel',
      garnish: 'Rueda de lima',
      categoria: 'clasicos',
      imagen: '/daiquiri.jpg',
    },
    {
      nombre: 'Gimlet',
      metodo: 'Agitar y servir en copa de cóctel',
      ingredientes: '2 oz de ginebra, 1 oz de jugo de lima fresco, 0.5 oz de jarabe simple',
      cristaleria: 'Copa de cóctel',
      garnish: 'Rueda de lima',
      categoria: 'clasicos',
      imagen: '/gimlet.jpg',
    },
    {
      nombre: 'Sazerac',
      metodo: 'Remover y servir en vaso Old Fashioned',
      ingredientes: '2 oz de ron blanco, 0.5 oz de jarabe de azúcar, 2 dashes de Peychaud’s Bitters, absenta',
      cristaleria: 'Vaso Old Fashioned',
      garnish: 'Cáscara de limón',
      categoria: 'clasicos',
      imagen: '/Sazerac.jpg',
    },
    {
      nombre: 'Sidecar',
      metodo: 'Agitar y servir en copa de cóctel',
      ingredientes: '2 oz de brandy, 0.75 oz de Cointreau, 0.75 oz de jugo de limón',
      cristaleria: 'Copa de cóctel',
      garnish: 'Twist de limón',
      categoria: 'clasicos',
      imagen: '/Sidecar.jpg',
    },
    {
      nombre: 'Manhattan',
      metodo: 'Revolver y servir en copa de cóctel',
      ingredientes: '2 oz de whisky de centeno, 1 oz de vermut rojo, 2 dashes de angostura',
      cristaleria: 'Copa de cóctel',
      garnish: 'Cereza',
      categoria: 'clasicos',
      imagen: '/Manhattan.jpg',
    },
    {
      nombre: 'Mai Tai',
      metodo: 'Agitar y servir en vaso lleno de hielo',
      ingredientes: '1.5 oz de ron blanco, 1.5 oz de ron oscuro, 0.75 oz de Cointreau, 0.5 oz de jarabe de almendra, 1 oz de jugo de limón, 0.25 oz de jarabe de azúcar',
      cristaleria: 'Vaso highball',
      garnish: 'Cereza y rodaja de piña',
      categoria: 'clasicos',
      imagen: '/MaiTai.jpg',
    },
    {
      nombre: 'Tom Collins',
      metodo: 'Revolver y servir en vaso highball',
      ingredientes: '2 oz de ginebra, 1 oz de jugo de limón, 0.5 oz de jarabe simple, agua con gas',
      cristaleria: 'Vaso highball',
      garnish: 'Rodaja de limón y cereza',
      categoria: 'clasicos',
      imagen: '/TomCollins.jpg',
    },
    {
      nombre: 'Bloody Mary',
      metodo: 'Agitar y servir en vaso highball',
      ingredientes: '1.5 oz de vodka, 3 oz de jugo de tomate, 0.5 oz de jugo de limón, 2 dashes de salsa Worcestershire, 2 dashes de salsa Tabasco, sal y pimienta',
      cristaleria: 'Vaso highball',
      garnish: 'Apio, rodaja de limón y lima, aceituna',
      categoria: 'clasicos',
      imagen: '/BloodyMary.jpg',
    },
    {
      nombre: 'Mint Julep',
      metodo: 'Revolver y servir en vaso con hielo picado',
      ingredientes: '2.5 oz de bourbon, 0.5 oz de jarabe de azúcar, hojas de menta',
      cristaleria: 'Vaso highball o julep',
      garnish: 'Ramas de menta',
      categoria: 'clasicos',
      imagen: '/MintJulep.jpg',
    },
    {
      nombre: 'Whisky Sour',
      metodo: 'Agitar y servir en vaso old fashioned',
      ingredientes: '2 oz de whisky, 0.75 oz de jugo de limón, 0.5 oz de jarabe simple',
      cristaleria: 'Vaso Old Fashioned',
      garnish: 'Cereza y rodaja de naranja',
      categoria: 'clasicos',
      imagen: '/WhiskySour.jpg',
    },
    {
      nombre: 'Caipirinha',
      metodo: 'Revolver y servir en vaso Old Fashioned',
      ingredientes: '2 oz de cachaça, 1 lima, 2 cucharaditas de azúcar',
      cristaleria: 'Vaso Old Fashioned',
      garnish: 'Rodaja de lima',
      categoria: 'clasicos',
      imagen: '/Caipirinha.jpg',
    },
    {
      nombre: 'White Russian',
      metodo: 'Revolver y servir en vaso Old Fashioned',
      ingredientes: '2 oz de vodka, 1 oz de licor de café, crema',
      cristaleria: 'Vaso Old Fashioned',
      garnish: 'Nuez moscada rallada',
      categoria: 'clasicos',
      imagen: '/WhiteRussian.jpg',
    },
    {
      nombre: 'Pisco Sour',
      metodo: 'Agitar y servir en copa de cóctel',
      ingredientes: '2 oz de pisco, 1 oz de jugo de limón, 0.75 oz de jarabe simple, clara de huevo',
      cristaleria: 'Copa de cóctel',
      garnish: 'Gotas de amargo de Angostura',
      categoria: 'clasicos',
      imagen: '/PiscoSour.jpg',
    },
    //Cocteles de autor
    {
      nombre: 'Refrescante',
      metodo: 'Mezclar y servir en vaso alto',
      ingredientes: '2 oz de licor, 1 oz de jugo de fruta, 0.5 oz de jarabe',
      cristaleria: 'Vaso alto',
      garnish: 'Decoración de autor',
      categoria: 'autor',
      imagen: '/mojito.jpg',
    },
    {
      nombre: 'Evas',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '2 oz de Sernova, 1 oz Apricot Brandy, 1 oz de Almibar Simple, 1 oz Jugo de Limon , 2 oz Jugo de Pomelo  ',
      cristaleria: 'Vaso Trago Largo',
      garnish: 'Gajo de Gelatina y Tintura de Frutos Rojos',
      categoria: 'autor',
      imagen: '/Evas.jpg',
    },
    {
      nombre: 'Love Potion N°1',
      metodo: 'Batido',
      ingredientes: '2 oz Absolut Pears, 1 oz de Almibar Simple, 1 oz de Jugo de Limon , 1 oz de Jugo Manzana Roja , 3 gotas de Bitter Angostura',
      cristaleria: 'Copa Coctel',
      garnish: 'Pincho de Cereza y Perfume de ElderFlower',
      categoria: 'autor',
      imagen: '/LovePotion.jpg',
    },
    {
      nombre: 'Black Flag',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '2 oz de havana añejo especial, 1 oz de Apricot brandy, 1 oz de Jugo de Limon , 1/2 oz de Jugo de Jengibre , 1/2 oz Jugo de Pomelo , 1 oz Almibar de Canela , 2 oz Jugo de Anana',
      cristaleria: 'Vaso Trago Largo',
      garnish: 'Penacho de Menta,Lima Deshidratada,Flor',
      categoria: 'autor',
      imagen: '/BlackFlag.jpg',
    },
    {
      nombre: 'Antonios Pool Party',
      metodo: 'Doble Batido',
      ingredientes: '2 oz de Carpano Rosso, 1/2 oz de Torrontes Tardio, 1 oz de Almibar de Canela , 1/2 oz Jugo de Limon , 1 oz Jugo de Pomelo , 1 oz Jugo de Manzana Verde , 2 golpes Bitter N°1 , Clara de Huevo',
      cristaleria: 'Vaso Corto',
      garnish: 'Rosa Mosqueta',
      categoria: 'autor',
      imagen: '/AntoniosParty.jpg',
    },
    {
      nombre: 'El secreto de Sophia',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '1 1/2 oz de Carpano Bianco, 1/4 oz de Sernova, 1/4 oz de Torrontes Tardio , 1 oz Almibar Simple , 1/2 oz Jugo de Limon , 1 oz Jugo de Pomelo , 1/2 oz Jugo de Jengibre , 2 golpes Bitter N°2',
      cristaleria: 'Vaso Corto',
      garnish: 'Penacho de Menta y Perfume de Branca Menta',
      categoria: 'autor',
      imagen: '/SecretoDeSofia.jpg',
    },
    {
      nombre: 'Cita en Milan',
      metodo: 'Batido con Hielo Rolo',
      ingredientes: '1 oz Punt e Mes, 1/2 oz Fernet Branca, 1 oz Almíbar Simple, 3/4 oz Jugo de Limón, 2 oz Jugo de Pera',
      cristaleria: 'Vaso Corto',
      garnish: 'Pera Deshidratada en Vino',
      categoria: 'autor',
      imagen: '/CitaEnMilan.jpg',
    },
    {
      nombre: 'Coco Bay',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '2 oz Malibú, 1 oz Jugo de Limón, 1 oz Almíbar Simple, 1 1/2 oz Jugo de Ananá, 1/2 oz Jugo de Pepino',
      cristaleria: 'Vaso Trago Largo',
      garnish: 'Penacho de Menta y Pepino',
      categoria: 'autor',
      imagen: '/CocoBay.jpg',
    },
    {
      nombre: 'Antidote',
      metodo: 'Batido y Doble Colado',
      ingredientes: '1 oz Sernova, 1 oz Torrontés Tardío, 1/2 oz Jugo de Jengibre, 1 oz Jugo de Limón, 1 1/2 oz Jugo de Pomelo, 1 oz Almíbar Simple , 1 oz Ramazzotti',
      cristaleria: 'Kitasato',
      garnish: 'Ahumado de Canela y Corcho con Flor',
      categoria: 'autor',
      imagen: '/Antidote.jpg',
    },
    {
      nombre: 'Brazilian Whitchcraft',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '2 oz Sernova, 1/2 Lima, 1 oz Jugo de Pomelo, 1/2 oz Miel, 1 oz Maracuyá, 1 Cucharada de Azúcar',
      cristaleria: 'Vaso Corto',
      garnish: 'Canela en Polvo y Lima con Flor',
      categoria: 'autor',
      imagen: '/Brazilian.jpg',
    },
    {
      nombre: 'Regalo de Dios',
      metodo: 'Batido y Doble Colado',
      ingredientes: '2 oz Brighton, 1 oz Martini Dry, 1 oz Jugo de Limón, 1 oz Almíbar Simple , 1/2 oz Jugo de Cranberry, 1 1/2 oz Té de Jazmín, 2 Gotas de Tintura de Cardamomo',
      cristaleria: 'Balon Quimica',
      garnish: 'Corcho con Flor',
      categoria: 'autor',
      imagen: '/RegaloDios.jpg',
    },
    {
      nombre: 'Dinastia Tang',
      metodo: 'Batido y Doble Colado',
      ingredientes: '2 oz Jameson, 1 1/2 oz Té Rojo, 1 oz Jugo de Manzana Roja, 1 oz Jugo de Limón, 1 oz Almíbar Simple',
      cristaleria: 'Copa de Martini',
      garnish: '',
      categoria: 'autor',
      imagen: '/Dinastia.jpg',
    },
    {
      nombre: 'Panty Spritz',
      metodo: 'Batido',
      ingredientes: '2 oz Ramazzotti, 2 oz Jugo de Ananá, 1/2 oz Maracuyá, 1/2 oz Almíbar Simple, 2 oz Espumante',
      cristaleria: 'Copón',
      garnish: 'Cereza y Hoja de Bambú',
      categoria: 'autor',
      imagen: '/PantySpritz.jpg',
    },
    {
      nombre: 'California Love',
      metodo: 'Batido',
      ingredientes: '2 oz Spirito Blu, 1/2 oz Almíbar Simple , 1 oz Jugo de Limón, 2 1/2 oz Cordial de Hibiscus y Té Rojo, 2 Golpes de Bitter N°3',
      cristaleria: 'Copa Coctel Chidaaa',
      garnish: 'Gomitas de Kumquat',
      categoria: 'autor',
      imagen: '/California.jpg',
    },
    {
      nombre: 'Matcha Royal',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '2 oz Chivas, 1 1/2 oz Cordial Matcha Manzanilla y Manzana Verde, 1/2 oz Jugo de Limón, 1 1/2 oz Sidra de Manzana Verde y Pera',
      cristaleria: 'Vaso Trago Largo',
      garnish: 'Penacho de Menta y Chocolate Blanco con Matcha',
      categoria: 'autor',
      imagen: '/Matcha.jpg',
    },
    {
      nombre: 'Fresquito Cubano',
      metodo: 'Batido con Hielo Picado',
      ingredientes: '1 1/2 oz Havana Especial, 1/2 oz Lillet Rosé, 1 1/2 oz Shrub de Manzana Verde y Pera, 3/4 oz Kirsch de Cerezas, 3 Gotas de Tintura de Eucalipto, 3/4 oz Jugo de Limón',
      cristaleria: 'Vaso Trago Largo',
      garnish: 'Hojas de Eucalipto y Rosa de Manzana Acaramelada',
      categoria: 'autor',
      imagen: '/Fresquito.jpg',
    },
    {
      nombre: 'Cosa Bella',
      metodo: 'Batido',
      ingredientes: '1 1/2 oz Ramazzotti, 1/2 oz Punt e Mes, 3/4 oz Miel, 3/4 oz Jugo de Limón, 3/4 oz Cordial de Naranja, 2 oz Jugo de Ananá, 3 Gotas de Bitter N°3',
      cristaleria: 'Copa Coupe',
      garnish: 'Pera Deshidratada',
      categoria: 'autor',
      imagen: '/CosaBella.jpg',
    },
    {
      nombre: 'Suspiro Andino',
      metodo: 'Batido Doble',
      ingredientes: '2 oz Mistral, 1/2 oz Almíbar Simple, 3/4 oz Carpano Rosso, 1 Golpe de Bitter de Chocolate, 2 1/2 oz Sabayón, 2 Gotas de Tintura de Lavanda',
      cristaleria: 'Copa Coupe',
      garnish: 'Cacao Amargo',
      categoria: 'autor',
      imagen: '/Suspiro.jpg',
    },
    {
      nombre: 'Siete Tres Cuartos',
      metodo: 'Batido Doble',
      ingredientes: '2 oz Jack Macerado en Galletitas, 1/2 oz Jugo de Manzana Roja, 1 oz Jugo de Lima, 1 oz Almíbar de Canela, 2 Gotas de Frangelico, 1 Clara de Huevo',
      cristaleria: 'Vaso Corto',
      garnish: 'Galletita con Sal Marina y Ralladura de Lima',
      categoria: 'autor',
      imagen: '/SieteTresCuartos.jpg',
    },
  ];
  
  module.exports = cocteles;